### ISSUE TITLE
Rainmeter doesn't do anything

### ISSUE THREAD

**Issue by nicking44** [Kapiainen/Lauhdutin#4]
When I select this skin from rainmeter it stops responding to user interactions (I.E I can't even right click and get the options there) and rainmeter stays around ~26% usage on my CPU. If I restart rainmeter with the skin active none of the other skins seem to load either and the process still idles at the same percentage. I have customize the skin to the needed changes. I'm using version 1.3.0 as well as version 3.3 of rainmeter (running as admin).

**Comment by nicking44** [comment]
Also if I need to change anything the only 2 files that seem to have anything in them is the Main.ini file and the UserSetting.inc file as well

**Comment by Kapiainen** [comment]
The skin is supposed to generate meters according to the settings found in *UserSettings.inc* and then refresh itself. If the skin cannot get permission to write to *Variables.inc*, then it may have gotten stuck.

**Comment by nicking44** [comment]
Is there a way I can get it unstuck? or is it just fucked and not going to work on my compluter/laptop?
The only changes I made to the Usersetting was the my userID and where steam is located and it still frezzing rainmeter. I have tried running rainmeter as admin and tried compatability mode (I'm on sindows 10) and the same issue happens no matter what I try to do to fix it.

**Comment by Wiggin38** [comment]
Hey Nick 
I had similar issues many months ago. I believe I fixed it by making sure I wasn't loading any weird other skins, just try loading this skin(Lauhdutin). I think I also had to reinstall Rainmeter at one point. 

Hopefully these idea's help.

**Comment by nicking44** [comment]
I just got around to trying thoese "soultoins" out Wiggin and the issue still persists even when I have this as the only skin running in admin mode.. I guess this skin was just not meant to be used by me. Even when the guy who made the skin gave me infomation that wasn't to helpful since it didn't even try to offer any solution to the issue. since he stated "that it may have gotten stuck".

**Comment by Kapiainen** [comment]
Do you have Rainmeter installed in the *Program Files* folder? It might be a case of restricted write permissions. I don't have Windows 10 so I'm not sure how strict that OS is about permissions. My impression of what other skins do is that they mostly only read files or use plugins to get information. I do not recommend turning off UAC (User Account Control) permanently, but you could try disabling it temporarily to see if that is interfering with Rainmeter's ability to write to the files that you found to be empty. Another thing that you could try is to install Rainmeter somewhere outside of *Program Files*, if you have it installed there at the moment.

**Comment by nicking44** [comment]
I do have it installed in the  Program Files folder. the only way I can install outside of the  Program Files folder is by installing the portable version. 

I installaed the the portable version onto my desktop and tried I tried loading the skin from there to no success even whil running in admin, compatability mode, turning UAC off, and loading with no other skins. The same issue persists.

**Comment by Atynine** [comment]
Solved by taking the Lauhdutin Folder out of the parent Lauhdutin folder and putting that one in your skins folder. Seems to be an issue with RainMeter, not this specific skin.
